import PDFDocument from 'pdfkit';

/**
 * Reusable PDFKit building blocks (payslips, reports, letters...).
 *
 * Usage:
 *   const doc = createPdf({ title: 'Headcount report' });
 *   brandHeader(doc, { organization: { name: org.name }, title: 'Headcount', subtitle: 'March 2026' });
 *   sectionTitle(doc, 'Summary');
 *   keyValueGrid(doc, [['Employees', '42'], ['Departments', '6']]);
 *   table(doc, { columns: [{ header: 'Name', width: 2 }, { header: 'Count', width: 1, align: 'right' }], rows });
 *   addPageFooters(doc, 'Generated by Stencil HRMS');
 *   const buffer = await renderPdf(doc);
 *
 * Only the built-in (WinAnsi) fonts are used, so text is passed through
 * `pdfText()` which replaces characters those fonts cannot render.
 */

export type Pdf = PDFKit.PDFDocument;

export const PDF_THEME = {
  brand: '#4f46e5',
  text: '#1f2330',
  muted: '#6b7280',
  border: '#e5e7eb',
  fill: '#f5f6fa',
  font: 'Helvetica',
  fontBold: 'Helvetica-Bold',
} as const;

export interface PdfMeta {
  title: string;
  author?: string;
  subject?: string;
  layout?: 'portrait' | 'landscape';
}

export const createPdf = (meta: PdfMeta): Pdf =>
  new PDFDocument({
    size: 'A4',
    layout: meta.layout ?? 'portrait',
    margins: { top: 40, bottom: 56, left: 40, right: 40 },
    bufferPages: true,
    info: { Title: meta.title, Author: meta.author ?? 'Stencil HRMS', Subject: meta.subject ?? meta.title, Creator: 'Stencil HRMS' },
  });

/** Replaces characters the standard PDF fonts cannot encode. */
export const pdfText = (value: unknown): string =>
  String(value ?? '')
    .replace(/•/g, '*')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[–—]/g, '-')
    // Keep tab/newlines and the WinAnsi range the built-in PDF fonts can render.
    // eslint-disable-next-line no-control-regex
    .replace(/[^\x09\x0A\x0D\x20-\x7E\xA0-\xFF]/g, '?');

const numberFormat = new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
export const formatAmount = (amount: number | null | undefined) => numberFormat.format(Number(amount ?? 0));
export const formatMoney = (amount: number | null | undefined, currency: string) => `${currency} ${formatAmount(amount)}`;

export const formatDate = (value: Date | string | null | undefined) => {
  if (!value) return '-';
  const d = typeof value === 'string' ? new Date(`${value.slice(0, 10)}T00:00:00Z`) : value;
  if (Number.isNaN(d.getTime())) return '-';
  return d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' });
};

export const contentLeft = (doc: Pdf) => doc.page.margins.left;
export const contentWidth = (doc: Pdf) => doc.page.width - doc.page.margins.left - doc.page.margins.right;
const bottomLimit = (doc: Pdf) => doc.page.height - doc.page.margins.bottom;

/** Starts a new page when fewer than `height` points remain. */
export const ensureSpace = (doc: Pdf, height: number) => {
  if (doc.y + height > bottomLimit(doc)) {
    doc.addPage();
    doc.y = doc.page.margins.top;
  }
};

export interface BrandHeaderOptions {
  organization: { name: string; addressLines?: string[] };
  title: string;
  subtitle?: string;
}

/** Organization block on the left, document title on the right, rule underneath. */
export const brandHeader = (doc: Pdf, opts: BrandHeaderOptions) => {
  const left = contentLeft(doc);
  const width = contentWidth(doc);
  const top = doc.page.margins.top;
  const initial = pdfText(opts.organization.name.trim().charAt(0).toUpperCase() || 'S');

  doc.save().roundedRect(left, top, 30, 30, 6).fill(PDF_THEME.brand).restore();
  doc.font(PDF_THEME.fontBold).fontSize(15).fillColor('#ffffff').text(initial, left, top + 8, { width: 30, align: 'center' });

  const textX = left + 40;
  const leftWidth = width * 0.6 - 40;
  doc.font(PDF_THEME.fontBold).fontSize(14).fillColor(PDF_THEME.text).text(pdfText(opts.organization.name), textX, top, { width: leftWidth });
  doc.font(PDF_THEME.font).fontSize(8.5).fillColor(PDF_THEME.muted);
  for (const line of (opts.organization.addressLines ?? []).filter(Boolean)) doc.text(pdfText(line), textX, doc.y, { width: leftWidth });
  const leftBottom = Math.max(doc.y, top + 30);

  const rightX = left + width * 0.6;
  doc.font(PDF_THEME.fontBold).fontSize(13).fillColor(PDF_THEME.brand).text(pdfText(opts.title), rightX, top, { width: width * 0.4, align: 'right' });
  if (opts.subtitle) {
    doc.font(PDF_THEME.font).fontSize(9).fillColor(PDF_THEME.muted).text(pdfText(opts.subtitle), rightX, doc.y + 2, { width: width * 0.4, align: 'right' });
  }
  const bottom = Math.max(leftBottom, doc.y) + 10;
  doc.save().moveTo(left, bottom).lineTo(left + width, bottom).lineWidth(1).strokeColor(PDF_THEME.border).stroke().restore();
  doc.x = left;
  doc.y = bottom + 12;
  doc.fillColor(PDF_THEME.text);
};

export const sectionTitle = (doc: Pdf, text: string) => {
  ensureSpace(doc, 30);
  const left = contentLeft(doc);
  doc.font(PDF_THEME.fontBold).fontSize(10).fillColor(PDF_THEME.brand).text(pdfText(text).toUpperCase(), left, doc.y, { width: contentWidth(doc), characterSpacing: 0.5 });
  doc.y += 4;
  doc.fillColor(PDF_THEME.text);
};

/** Label/value pairs laid out in N columns. */
export const keyValueGrid = (doc: Pdf, rows: [string, string][], opts: { columns?: number; labelWidth?: number } = {}) => {
  const columns = opts.columns ?? 2;
  const left = contentLeft(doc);
  const colWidth = contentWidth(doc) / columns;
  const labelWidth = opts.labelWidth ?? Math.min(110, colWidth * 0.45);
  for (let i = 0; i < rows.length; i += columns) {
    const chunk = rows.slice(i, i + columns);
    const heights = chunk.map(([, value]) => doc.font(PDF_THEME.font).fontSize(9).heightOfString(pdfText(value), { width: colWidth - labelWidth - 8 }));
    const rowHeight = Math.max(14, ...heights) + 3;
    ensureSpace(doc, rowHeight);
    const y = doc.y;
    chunk.forEach(([label, value], idx) => {
      const x = left + idx * colWidth;
      doc.font(PDF_THEME.font).fontSize(8.5).fillColor(PDF_THEME.muted).text(pdfText(label), x, y, { width: labelWidth });
      doc.font(PDF_THEME.fontBold).fontSize(9).fillColor(PDF_THEME.text).text(pdfText(value || '-'), x + labelWidth, y, { width: colWidth - labelWidth - 8 });
    });
    doc.y = y + rowHeight;
  }
  doc.x = left;
  doc.y += 6;
};

export interface TableColumn {
  header: string;
  /** Relative width weight. */
  width?: number;
  align?: 'left' | 'right' | 'center';
}

export interface TableOptions {
  columns: TableColumn[];
  rows: (string | number)[][];
  /** Bold, shaded last row (e.g. totals). */
  footer?: (string | number)[];
  x?: number;
  y?: number;
  width?: number;
  fontSize?: number;
  zebra?: boolean;
  emptyText?: string;
}

/** Draws a table with header repetition across page breaks. Returns the y below the table. */
export const table = (doc: Pdf, opts: TableOptions) => {
  const x = opts.x ?? contentLeft(doc);
  const width = opts.width ?? contentWidth(doc);
  const fontSize = opts.fontSize ?? 9;
  const pad = 5;
  const totalWeight = opts.columns.reduce((s, c) => s + (c.width ?? 1), 0);
  const widths = opts.columns.map((c) => (width * (c.width ?? 1)) / totalWeight);
  let y = opts.y ?? doc.y;

  const rowHeight = (cells: (string | number)[], bold = false) =>
    Math.max(
      ...cells.map((cell, i) =>
        doc
          .font(bold ? PDF_THEME.fontBold : PDF_THEME.font)
          .fontSize(fontSize)
          .heightOfString(pdfText(cell), { width: widths[i]! - pad * 2 }),
      ),
      fontSize,
    ) +
    pad * 2;

  const drawRow = (cells: (string | number)[], opt: { bold?: boolean; fill?: string; color?: string }) => {
    const h = rowHeight(cells, opt.bold);
    if (y + h > bottomLimit(doc)) {
      doc.addPage();
      y = doc.page.margins.top;
      if (!opt.bold || opt.fill !== PDF_THEME.brand) drawHeader();
    }
    if (opt.fill) doc.save().rect(x, y, width, h).fill(opt.fill).restore();
    let cx = x;
    cells.forEach((cell, i) => {
      doc
        .font(opt.bold ? PDF_THEME.fontBold : PDF_THEME.font)
        .fontSize(fontSize)
        .fillColor(opt.color ?? PDF_THEME.text)
        .text(pdfText(cell), cx + pad, y + pad, { width: widths[i]! - pad * 2, align: opts.columns[i]?.align ?? 'left' });
      cx += widths[i]!;
    });
    doc.save().moveTo(x, y + h).lineTo(x + width, y + h).lineWidth(0.5).strokeColor(PDF_THEME.border).stroke().restore();
    y += h;
  };

  const drawHeader = () => drawRow(opts.columns.map((c) => c.header), { bold: true, fill: PDF_THEME.brand, color: '#ffffff' });

  drawHeader();
  if (!opts.rows.length && opts.emptyText) {
    drawRow([opts.emptyText, ...opts.columns.slice(1).map(() => '')], { color: PDF_THEME.muted });
  }
  opts.rows.forEach((row, idx) => drawRow(row, { fill: opts.zebra && idx % 2 === 1 ? PDF_THEME.fill : undefined }));
  if (opts.footer) drawRow(opts.footer, { bold: true, fill: PDF_THEME.fill });

  doc.x = contentLeft(doc);
  doc.y = y + 8;
  doc.fillColor(PDF_THEME.text);
  return y;
};

/** Highlighted single-line callout (e.g. "Net pay: USD 1,234.00"). */
export const callout = (doc: Pdf, label: string, value: string, note?: string) => {
  ensureSpace(doc, note ? 54 : 40);
  const left = contentLeft(doc);
  const width = contentWidth(doc);
  const y = doc.y;
  const h = note ? 46 : 32;
  doc.save().roundedRect(left, y, width, h, 6).fill(PDF_THEME.fill).restore();
  doc.font(PDF_THEME.fontBold).fontSize(11).fillColor(PDF_THEME.text).text(pdfText(label), left + 12, y + 10, { width: width / 2 });
  doc.font(PDF_THEME.fontBold).fontSize(13).fillColor(PDF_THEME.brand).text(pdfText(value), left + width / 2, y + 9, { width: width / 2 - 12, align: 'right' });
  if (note) doc.font(PDF_THEME.font).fontSize(8.5).fillColor(PDF_THEME.muted).text(pdfText(note), left + 12, y + 28, { width: width - 24 });
  doc.x = left;
  doc.y = y + h + 12;
  doc.fillColor(PDF_THEME.text);
};

export const paragraph = (doc: Pdf, text: string, opts: { muted?: boolean; size?: number } = {}) => {
  doc
    .font(PDF_THEME.font)
    .fontSize(opts.size ?? 9)
    .fillColor(opts.muted ? PDF_THEME.muted : PDF_THEME.text)
    .text(pdfText(text), contentLeft(doc), doc.y, { width: contentWidth(doc) });
  doc.y += 4;
  doc.fillColor(PDF_THEME.text);
};

/** Footer text + "Page X of Y" on every page. Call once, after all content. */
export const addPageFooters = (doc: Pdf, text: string) => {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const bottomMargin = doc.page.margins.bottom;
    doc.page.margins.bottom = 0; // allow writing inside the bottom margin without adding pages
    const left = doc.page.margins.left;
    const width = doc.page.width - left - doc.page.margins.right;
    const y = doc.page.height - bottomMargin + 18;
    doc.save().moveTo(left, y - 6).lineTo(left + width, y - 6).lineWidth(0.5).strokeColor(PDF_THEME.border).stroke().restore();
    doc.font(PDF_THEME.font).fontSize(7.5).fillColor(PDF_THEME.muted);
    doc.text(pdfText(text), left, y, { width: width * 0.75, lineBreak: false });
    doc.text(`Page ${i - range.start + 1} of ${range.count}`, left + width * 0.75, y, { width: width * 0.25, align: 'right', lineBreak: false });
    doc.page.margins.bottom = bottomMargin;
  }
};

/** Finalizes the document and resolves with its bytes. */
export const renderPdf = (doc: Pdf): Promise<Buffer> =>
  new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
